version: "3.7"
services:
  backend:
    build: builder
    # build: backend
    ports:
      - "8000:8000"
    depends_on: 
      - db
    container_name: "app-backend"
  redis:
    image: redis
    container_name: "my-redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /dockerShareFile/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /dockerShareFile/redis/data:/data
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: "mysql-backend"
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_ROOT_HOST=%
secrets:
  db-password:
    file: config/db_password.txt
